// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedCookbook.Infrastructure.Data;

#nullable disable

namespace SharedCookbook.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("00000000000001_SquashedInitialSchema")]
    partial class SquashedInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.Cookbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_cookbook_id");

                    b.HasIndex(new[] { "CreatedBy" }, "IX_cookbook_creator__created_by");

                    b.ToTable("cookbook", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_invitation_id");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipientPersonId")
                        .HasColumnType("text")
                        .HasColumnName("recipient_person_id");

                    b.Property<DateTimeOffset?>("ResponseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_date");

                    b.Property<string>("SenderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invitation_status");

                    b.HasKey("Id")
                        .HasName("PK_cookbook_invitation_id");

                    b.HasIndex(new[] { "CookbookId" }, "IX_cookbook_invitation__cookbook_id");

                    b.HasIndex(new[] { "CreatedBy" }, "IX_cookbook_invitation__created_by");

                    b.HasIndex(new[] { "RecipientPersonId" }, "IX_cookbook_invitation__recipient_person_id");

                    b.ToTable("cookbook_invitation", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_member_id");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("PK_cookbook_member_id");

                    b.HasIndex(new[] { "CookbookId" }, "IX_cookbook_member__cookbook_id");

                    b.HasIndex(new[] { "CreatedBy" }, "IX_cookbook_member__created_by");

                    b.HasIndex(new[] { "CookbookId", "CreatedBy" }, "UX_cookbook_member__cookbook_user")
                        .IsUnique();

                    b.ToTable("cookbook_member", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_notification_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActorDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("SubjectDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectUserId")
                        .HasColumnType("text")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("PK_cookbook_notification_id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("SubjectUserId");

                    b.HasIndex(new[] { "CookbookId" }, "IX_cookbook_notification__cookbook_id");

                    b.HasIndex(new[] { "RecipeId" }, "IX_cookbook_notification__recipe_id");

                    b.HasIndex(new[] { "RecipientUserId", "Created" }, "IX_cookbook_notification__recipient_created");

                    b.HasIndex(new[] { "RecipientUserId" }, "IX_cookbook_notification__recipient_user_id");

                    b.ToTable("cookbook_notification", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.IngredientCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_category_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_ingredient_category_id");

                    b.HasIndex(new[] { "RecipeId" }, "IX_ingredient__category_recipe_id");

                    b.ToTable("ingredient_category", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.InvitationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_token_id");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RedeemerPersonId")
                        .HasColumnType("text")
                        .HasColumnName("redeemer_person_id");

                    b.Property<DateTimeOffset?>("ResponseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invitation_status");

                    b.HasKey("Id")
                        .HasName("invitation_token_id");

                    b.HasIndex("CookbookId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PublicId")
                        .HasDatabaseName("IX_invitation_token__public_id");

                    b.ToTable("invitation_token", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("AuthorDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("cookbook_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MadeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("made_count");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("summary");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("video_path");

                    b.HasKey("Id")
                        .HasName("PK_recipe_id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "CookbookId" }, "IX_recipe__cookbook_id");

                    b.ToTable("recipe", (string)null);
                });

            modelBuilder.Entity("SharedCookbook.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.Cookbook", b =>
                {
                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_cookbook__created_by");
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookInvitation", b =>
                {
                    b.HasOne("SharedCookbook.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Invitations")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cookbook_invitation__cookbook_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_cookbook_invitation__created_by");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientPersonId")
                        .HasConstraintName("FK_cookbook_invitation__recipient_person_id");

                    b.Navigation("Cookbook");
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookMembership", b =>
                {
                    b.HasOne("SharedCookbook.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Memberships")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cookbook_member__cookbook_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cookbook_member__created_by");

                    b.Navigation("Cookbook");
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.CookbookNotification", b =>
                {
                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_cookbook_notification__actor_user_id");

                    b.HasOne("SharedCookbook.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Notifications")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cookbook_notification__cookbook_id");

                    b.HasOne("SharedCookbook.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_cookbook_notification__recipe_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cookbook_notification__recipient_user_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_cookbook_notification__subject_user_id");

                    b.Navigation("Cookbook");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.IngredientCategory", b =>
                {
                    b.HasOne("SharedCookbook.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ingredient_category__recipe_id");
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.InvitationToken", b =>
                {
                    b.HasOne("SharedCookbook.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_invitation_token__cookbook_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_invitation_token__created_by");

                    b.OwnsOne("SharedCookbook.Domain.ValueObjects.TokenDigest", "Digest", b1 =>
                        {
                            b1.Property<Guid>("InvitationTokenId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("token_hash");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("token_salt");

                            b1.HasKey("InvitationTokenId");

                            b1.ToTable("invitation_token");

                            b1.WithOwner()
                                .HasForeignKey("InvitationTokenId");
                        });

                    b.Navigation("Cookbook");

                    b.Navigation("Digest")
                        .IsRequired();
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("SharedCookbook.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Recipes")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recipe__cookbook_id");

                    b.HasOne("SharedCookbook.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_recipe__created_by");

                    b.OwnsMany("SharedCookbook.Domain.Entities.IngredientSection", "IngredientSections", b1 =>
                        {
                            b1.Property<Guid>("RecipeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Ordinal");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.HasKey("RecipeId", "__synthesizedOrdinal");

                            b1.ToTable("recipe");

                            b1
                                .ToJson("ingredient_sections")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsMany("SharedCookbook.Domain.Entities.RecipeIngredient", "Ingredients", b2 =>
                                {
                                    b2.Property<Guid>("IngredientSectionRecipeId");

                                    b2.Property<int>("IngredientSection__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(255);

                                    b2.Property<bool>("Optional");

                                    b2.Property<int>("Ordinal");

                                    b2.HasKey("IngredientSectionRecipeId", "IngredientSection__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("recipe");

                                    b2.WithOwner()
                                        .HasForeignKey("IngredientSectionRecipeId", "IngredientSection__synthesizedOrdinal");
                                });

                            b1.Navigation("Ingredients");
                        });

                    b.OwnsMany("SharedCookbook.Domain.Entities.RecipeDirection", "Directions", b1 =>
                        {
                            b1.Property<Guid>("RecipeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Image")
                                .HasMaxLength(2048);

                            b1.Property<int>("Ordinal");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2048);

                            b1.HasKey("RecipeId", "__synthesizedOrdinal");

                            b1.ToTable("recipe");

                            b1
                                .ToJson("directions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("SharedCookbook.Domain.Entities.RecipeImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("RecipeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(2048);

                            b1.Property<int>("Ordinal");

                            b1.HasKey("RecipeId", "__synthesizedOrdinal");

                            b1.ToTable("recipe");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("SharedCookbook.Domain.Entities.RecipeNutrition", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("RecipeId");

                            b1.Property<int?>("Calories");

                            b1.Property<int?>("Carbohydrates");

                            b1.Property<int?>("Fat");

                            b1.Property<int?>("Fiber");

                            b1.Property<int?>("Protein");

                            b1.Property<int?>("Sodium");

                            b1.Property<int?>("Sugar");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipe");

                            b1
                                .ToJson("nutrition")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("SharedCookbook.Domain.ValueObjects.DietaryTags", "DietaryTags", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("IsCheap")
                                .HasColumnType("boolean")
                                .HasColumnName("IsCheap");

                            b1.Property<bool?>("IsDairyFree")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDairyFree");

                            b1.Property<bool?>("IsGlutenFree")
                                .HasColumnType("boolean")
                                .HasColumnName("IsGlutenFree");

                            b1.Property<bool?>("IsHealthy")
                                .HasColumnType("boolean")
                                .HasColumnName("IsHealthy");

                            b1.Property<bool?>("IsHighProtein")
                                .HasColumnType("boolean")
                                .HasColumnName("IsHighProtein");

                            b1.Property<bool?>("IsLowFodmap")
                                .HasColumnType("boolean")
                                .HasColumnName("IsLowFodmap");

                            b1.Property<bool?>("IsVegan")
                                .HasColumnType("boolean")
                                .HasColumnName("IsVegan");

                            b1.Property<bool?>("IsVegetarian")
                                .HasColumnType("boolean")
                                .HasColumnName("IsVegetarian");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipe");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("SharedCookbook.Domain.ValueObjects.MealTypes", "MealTypes", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("IsBreakfast")
                                .HasColumnType("boolean")
                                .HasColumnName("IsBreakfast");

                            b1.Property<bool?>("IsDessert")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDessert");

                            b1.Property<bool?>("IsDinner")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDinner");

                            b1.Property<bool?>("IsLunch")
                                .HasColumnType("boolean")
                                .HasColumnName("IsLunch");

                            b1.Property<bool?>("IsSnack")
                                .HasColumnType("boolean")
                                .HasColumnName("IsSnack");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipe");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("SharedCookbook.Domain.ValueObjects.Timing", "Timing", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("BakingMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("baking_time_in_minutes");

                            b1.Property<int?>("CookingMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("cooking_time_in_minutes");

                            b1.Property<int?>("PreparationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("preparation_time_in_minutes");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipe");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Cookbook");

                    b.Navigation("DietaryTags")
                        .IsRequired();

                    b.Navigation("Directions");

                    b.Navigation("Images");

                    b.Navigation("IngredientSections");

                    b.Navigation("MealTypes")
                        .IsRequired();

                    b.Navigation("Nutrition");

                    b.Navigation("Timing")
                        .IsRequired();
                });

            modelBuilder.Entity("SharedCookbook.Domain.Entities.Cookbook", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Memberships");

                    b.Navigation("Notifications");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
