mode: ContinuousDelivery

branches:
  main:
    regex: ^(master|main)$
    increment: Patch

  develop:
    regex: ^dev(elop)?$
    tag: beta
    increment: Minor

  feature:
    regex: ^feature[/-]
    tag: alpha
    increment: Patch
