mode: ContinuousDelivery

branches:
  main:
    regex: ^(master|main)$
    increment: Patch
    label: null

  develop:
    regex: ^dev(elop)?$
    label: beta
    increment: Minor

  feature:
    regex: ^feature[/-]
    label: alpha
    increment: Patch
