version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=SharedCookbookDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"   # HTTP only
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # This explicitly tells ASP.NET to use the “database” service, not localhost
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=SharedCookbookDb;Username=postgres;Password=admin;"
