<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SharedCookbook.Tests.Shared</RootNamespace>
    <AssemblyName>SharedCookbook.Tests.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Web\Web.csproj" />
  </ItemGroup>

</Project>
