<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SharedCookbook.Application</RootNamespace>
        <AssemblyName>SharedCookbook.Application</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
  
    <ItemGroup>
        <InternalsVisibleTo Include="SharedCookbook.Application.UnitTests" />
    </ItemGroup>

</Project>
