name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version via GitVersion
        id: gitversion
        uses: gittools/actions/gitversion@v0.9.14

      - name: Show GitVersion info
        run: |
          echo "FullSemVer      = ${{ steps.gitversion.outputs.FullSemVer }}"
          echo "SemVer          = ${{ steps.gitversion.outputs.SemVer }}"
          echo "AssemblySemVer  = ${{ steps.gitversion.outputs.AssemblySemVer }}"
          echo "NuGetVersionV2  = ${{ steps.gitversion.outputs.NuGetVersionV2 }}"

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution (skip NSwag)
        run: |
          dotnet build --no-restore -c Release \
            /p:Version=${{ steps.gitversion.outputs.FullSemVer }} \
            /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} \
            /p:FileVersion=${{ steps.gitversion.outputs.AssemblySemVer }} \
            -p:SkipNSwag=true

      - name: Run tests (skip NSwag)
        run: |
          dotnet test --no-build -c Release \
            /p:Version=${{ steps.gitversion.outputs.FullSemVer }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: |
            Release ${{ github.ref_name }}:
            - (add your changelog or notes here)
