name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout with full history so GitVersion can inspect tags/commits
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) install the GitVersion tool (no need to pick a version manually—this just fetches it)
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'      # pick the GitVersion CLI version line you want (e.g. 5.x)

      # 3) run GitVersion → outputs get exposed automatically
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true     # (optional) if you have a GitVersion.yml at repo root
          configFilePath: GitVersion.yml

      # 4) show what GitVersion computed
      - name: Show GitVersion info
        run: |
          echo "FullSemVer      = ${{ steps.gitversion.outputs.FullSemVer }}"
          echo "SemVer          = ${{ steps.gitversion.outputs.SemVer }}"
          echo "AssemblySemVer  = ${{ steps.gitversion.outputs.AssemblySemVer }}"
          echo "NuGetVersionV2  = ${{ steps.gitversion.outputs.NuGetVersionV2 }}"

      # 5) .NET SDK setup
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # 6) restore, build, test—all using the version GitVersion provided
      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution (skip NSwag)
        run: |
          dotnet build --no-restore -c Release \
            /p:Version=${{ steps.gitversion.outputs.FullSemVer }} \
            /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} \
            /p:FileVersion=${{ steps.gitversion.outputs.AssemblySemVer }} \
            -p:SkipNSwag=true

      - name: Run tests (skip NSwag)
        run: |
          dotnet test --no-build -c Release \
            /p:Version=${{ steps.gitversion.outputs.FullSemVer }}

      # 7) create a GitHub release if this was triggered by a tag "vX.Y.Z"
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: |
            Release ${{ github.ref_name }}:
            - (add your changelog or notes here)
